server:
  port: 8080

spring:
  application:
    name: candidates-api
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy
  jmx:
    enabled: off
  main:
    banner-mode: "OFF"
  resources:
    add-mappings: on
  datasource:
    url: jdbc:mysql://localhost:3306/bdd?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 5 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 10 #maximum pool size
      idle-timeout: 10000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: on #default auto-commit behavior.
  jpa:
    hibernate.ddl-auto: update
    show-sql: on